require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

# Required by @react-native-firebase: FirebaseAuth is a Swift pod whose
# transitive Obj-C dependencies (GoogleUtilities, FirebaseAuthInterop,
# FirebaseAppCheckInterop, RecaptchaInterop) must expose clang module maps
# before they can be linked statically.
use_modular_headers!

prepare_react_native_project!

target 'DarthPixit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
